In [6]:
# Loading the dataset 
import pandas as pd

file_name = "https://raw.githubusercontent.com/rajeevratan84/datascienceforbusiness/master/amazon_fires.csv"
df = pd.read_csv(file_name, encoding='latin-1')
df.head()

    ano      mes estado   numero  encontro
0  1998  Janeiro   Acre  0 Fires  1/1/1998
1  1999  Janeiro   Acre  0 Fires  1/1/1999
2  2000  Janeiro   Acre  0 Fires  1/1/2000
3  2001  Janeiro   Acre  0 Fires  1/1/2001
4  2002  Janeiro   Acre  0 Fires  1/1/2002

In [7]:
#To check the regions in the dataset
df['estado'].unique()

array(['Acre', 'alagoas', 'Amapa', 'Amazonas', 'Bahia', 'Ceara',
       'Distrito Federal', 'Espirito Santo', 'Goias', 'Maranhao',
       'Mato Grosso', 'Minas Gerais', 'pará', 'Paraiba', 'Pernambuco',
       'Piau', 'Rio', 'rondonia', 'Roraima', 'Santa Catarina',
       'Sao Paulo', 'Sergipe', 'Tocantins'], dtype=object)

# Renaming the columns to English

In [9]:
new_columns_names = {
    'ano' : 'year',
    'mes' : 'month',
    'estado' : 'state',
    'numero': 'number_of_fires',
    'encontro': 'date'
}
df.rename(columns = new_columns_names, inplace = True)

In [10]:
df.head()

   year    month state number_of_fires      date
0  1998  Janeiro  Acre         0 Fires  1/1/1998
1  1999  Janeiro  Acre         0 Fires  1/1/1999
2  2000  Janeiro  Acre         0 Fires  1/1/2000
3  2001  Janeiro  Acre         0 Fires  1/1/2001
4  2002  Janeiro  Acre         0 Fires  1/1/2002

In [11]:
df['year'].unique()

array([1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008,
       2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017], dtype=int64)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   year             5 non-null      int64
 1   month            5 non-null      object
 2   state            5 non-null      object
 3   number_of_fires  5 non-null      object
 4   date             5 non-null      object
dtypes: int64(1), object(4)
memory usage: 332.0+ bytes

# Rearranging the columns

In [18]:
# reordering the columns accordingly
new_order = [4,1,0,2,3]
df = df[df.columns[new_order]]
df.head()

       date    month  year state number_of_fires
0  1/1/1998  Janeiro  1998  Acre         0 Fires
1  1/1/1999  Janeiro  1999  Acre         0 Fires
2  1/1/2000  Janeiro  2000  Acre         0 Fires
3  1/1/2001  Janeiro  2001  Acre         0 Fires
4  1/1/2002  Janeiro  2002  Acre         0 Fires

# Determining if a column contains numeric data

In [19]:
# it isn't, let's find our why
df['number_of_fires'].str.isnumeric()

0    False
1    False
2    False
3    False
4    False
Name: number_of_fires, dtype: bool

In [22]:
df['number_of_fires'].astype(str).str.isdigit()

0    False
1    False
2    False
3    False
4    False
Name: number_of_fires, dtype: bool

# Removing the unecessay text from the columns

In [24]:
# using strip to remove the spaces and then checking if the values are numeric
df['number_of_fires'].str.strip("Fires")

0    0
1    0
2    0
3    0
4    0
Name: number_of_fires, dtype: object

In [25]:
# Replacing the column with the cleaned column
df['number_of_fires'] = df['number_of_fires'].str.strip("Fires").astype(int)
df.head()

       date    month  year state  number_of_fires
0  1/1/1998  Janeiro  1998  Acre                0
1  1/1/1999  Janeiro  1999  Acre                0
2  1/1/2000  Janeiro  2000  Acre                0
3  1/1/2001  Janeiro  2001  Acre                0
4  1/1/2002  Janeiro  2002  Acre                0

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             5 non-null      object
 1   month            5 non-null      object
 2   year             5 non-null      int64
 3   state            5 non-null      object
 4   number_of_fires  5 non-null      int32
dtypes: int32(1), int64(1), object(3)
memory usage: 312.0+ bytes

In [29]:
# conveting the number of fires to a float data type and also this is the alternative string manipulation method to remove the "Fires" string from the column
# df["number_of_fires"] = df["number_of_fires"].str.replace("", "0").astype(float)
# df.head()
print(df["number_of_fires"].dtype)
print(df["number_of_fires"].head())

int32
0    0
1    0
2    0
3    0
4    0
Name: number_of_fires, dtype: int32

In [30]:
# If it's already numeric — just convert directly, no str needed
df["number_of_fires"] = df["number_of_fires"].astype(float)

# If it's mixed (some strings, some numbers) — convert safely
df["number_of_fires"] = pd.to_numeric(df["number_of_fires"], errors='coerce').fillna(0)

In [31]:
df.head()

       date    month  year state  number_of_fires
0  1/1/1998  Janeiro  1998  Acre              0.0
1  1/1/1999  Janeiro  1999  Acre              0.0
2  1/1/2000  Janeiro  2000  Acre              0.0
3  1/1/2001  Janeiro  2001  Acre              0.0
4  1/1/2002  Janeiro  2002  Acre              0.0

# Handelling the missing values

In [ ]:
# reloding the dataset
file_naam = "https://raw.githubusercontent.com/rajeevratan84/datascienceforbusiness/master/amazon_fires.csv"
df = pd.read_csv(file_naam, encoding='latin-1')
naya_columns = {
    'ano' : 'year',
    'mes' : 'month',
    'estado' : 'state',
    'numero': 'number_of_fires',
    'encontro': 'date'
}
df.rename(columns = naya_columns, inplace = True)
df['number_of_fires'] = df['number_of_fires'].str.strip("Fires")
#creating a true copy of the dataset
df_copy = df.copy()
df_copy.head()

   year    month state number_of_fires      date
0  1998  Janeiro  Acre              0   1/1/1998
1  1999  Janeiro  Acre              0   1/1/1999
2  2000  Janeiro  Acre              0   1/1/2000
3  2001  Janeiro  Acre              0   1/1/2001
4  2002  Janeiro  Acre              0   1/1/2002

In [34]:
df_copy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6454 entries, 0 to 6453
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   year             6454 non-null   int64
 1   month            6454 non-null   object
 2   state            6454 non-null   object
 3   number_of_fires  6322 non-null   object
 4   date             6454 non-null   object
dtypes: int64(1), object(4)
memory usage: 252.2+ KB

In [35]:
df_copy.isnull().sum()

year                 0
month                0
state                0
number_of_fires    132
date                 0
dtype: int64

In [38]:
#  we easily remove the NUll or Nan (not a number) values from the dataset using the dropna() method    
df_copy.dropna(inplace = True)
df_copy.reset_index()
df_copy.head()

   year    month state number_of_fires      date
0  1998  Janeiro  Acre              0   1/1/1998
1  1999  Janeiro  Acre              0   1/1/1999
2  2000  Janeiro  Acre              0   1/1/2000
3  2001  Janeiro  Acre              0   1/1/2001
4  2002  Janeiro  Acre              0   1/1/2002

In [39]:
df_copy.isnull().sum()

year               0
month              0
state              0
number_of_fires    0
date               0
dtype: int64

# Other MEthods of handelling missing values

In [42]:
# reloding the dataset to check if the changes are permanent
file_naam = "https://raw.githubusercontent.com/rajeevratan84/datascienceforbusiness/master/amazon_fires.csv"
df = pd.read_csv(file_naam, encoding='latin-1')    
new_columns_names = {
    'ano' : 'year',
    'mes' : 'month', 
    'estado' : 'state',
    'numero': 'number_of_fires',    
    'encontro': 'date'
}
df.rename(columns = new_columns_names, inplace = True)

df['number_of_fires'] = df['number_of_fires'].str.strip("Fires")
df_kapy = df.copy()
df.head()

   year    month state number_of_fires      date
0  1998  Janeiro  Acre              0   1/1/1998
1  1999  Janeiro  Acre              0   1/1/1999
2  2000  Janeiro  Acre              0   1/1/2000
3  2001  Janeiro  Acre              0   1/1/2001
4  2002  Janeiro  Acre              0   1/1/2002

In [43]:
df.isnull().sum()

year                 0
month                0
state                0
number_of_fires    132
date                 0
dtype: int64

In [48]:
df[df['number_of_fires'].isnull()].head ()

     year     month state number_of_fires      date
68   2006     Abril  Acre             NaN  1/1/2006
110  2008     Junho  Acre             NaN  1/1/2008
127  2005     Julho  Acre             NaN  1/1/2005
206  2004  Novembro  Acre             NaN  1/1/2004
217  2015  Novembro  Acre             NaN  1/1/2015

##### what to do with the missing data? 
1. remove them using dropn(axis = 0 )
2 . replace them with some arbitary number (e.g. an average)
3 . replace them zeros , or forward fill method or backward fill

In [64]:
#using fillna with zeros
df = df_kapy
df['number_of_fires'] = df['number_of_fires'].fillna(0)
df.head(70)

    year    month state number_of_fires      date
0   1998  Janeiro  Acre              0   1/1/1998
1   1999  Janeiro  Acre              0   1/1/1999
2   2000  Janeiro  Acre              0   1/1/2000
3   2001  Janeiro  Acre              0   1/1/2001
4   2002  Janeiro  Acre              0   1/1/2002
..   ...      ...   ...             ...       ...
65  2003    Abril  Acre              1   1/1/2003
66  2004    Abril  Acre              2   1/1/2004
67  2005    Abril  Acre              1   1/1/2005
68  2006    Abril  Acre               0  1/1/2006
69  2007    Abril  Acre              0   1/1/2007

[70 rows x 5 columns]

In [60]:
# lets try with the filling 
df['number_of_fires'] = df['number_of_fires'].fillna(method = 'ffill')
df.head(70)

C:\Users\Acer\AppData\Local\Temp\ipykernel_12692\2943543932.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['number_of_fires'] = df['number_of_fires'].fillna(method = 'ffill')

    year    month state number_of_fires      date
0   1998  Janeiro  Acre              0   1/1/1998
1   1999  Janeiro  Acre              0   1/1/1999
2   2000  Janeiro  Acre              0   1/1/2000
3   2001  Janeiro  Acre              0   1/1/2001
4   2002  Janeiro  Acre              0   1/1/2002
..   ...      ...   ...             ...       ...
65  2003    Abril  Acre              1   1/1/2003
66  2004    Abril  Acre              2   1/1/2004
67  2005    Abril  Acre              1   1/1/2005
68  2006    Abril  Acre              1   1/1/2006
69  2007    Abril  Acre              1   1/1/2007

[70 rows x 5 columns]

In [58]:
# view index 444 to see how it changes
df.iloc[444]

year                   2002
month              Novembro
state               alagoas
number_of_fires          1
date               1/1/2002
Name: 444, dtype: object

# Replacing text in columns

# Data integration

In [6]:
import pandas as pd
# reloding the dataset to check if the changes are permanent
file_naam = "https://raw.githubusercontent.com/rajeevratan84/datascienceforbusiness/master/amazon_fires.csv"
df = pd.read_csv(file_naam, encoding='latin-1')    
new_columns_names = {
    'ano' : 'year',
    'mes' : 'month', 
    'estado' : 'state',
    'numero': 'number_of_fires',    
    'encontro': 'date'
}
df.rename(columns = new_columns_names, inplace = True)
df['state'] = df['state'].str.title()

df.head()
df['number_of_fires'] = df['number_of_fires'].str.strip("Fires")
df['number_of_fires'] = df['number_of_fires'].fillna(0)
df['number_of_fires'] = df['number_of_fires'].astype(float)

# introducing the map function
month_translations = {
    'Janeiro': 'January',
    'Fevereiro': 'February',
    'Março': 'March',

    'Abril': 'April',
    'Maio': 'May',
    'Junho': 'June',
    'Julho': 'July',
    'Agosto': 'August',
    'Setembro': 'September',
    'Outubro': 'October',
    'Novembro': 'November',
    'Dezembro': 'December'
}
df['month'] = df['month'].map(month_translations)
df.head(20)

    year    month state  number_of_fires      date
0   1998  January  Acre              0.0  1/1/1998
1   1999  January  Acre              0.0  1/1/1999
2   2000  January  Acre              0.0  1/1/2000
3   2001  January  Acre              0.0  1/1/2001
4   2002  January  Acre              0.0  1/1/2002
5   2003  January  Acre             10.0  1/1/2003
6   2004  January  Acre              0.0  1/1/2004
7   2005  January  Acre             12.0  1/1/2005
8   2006  January  Acre              4.0  1/1/2006
9   2007  January  Acre              0.0  1/1/2007
10  2008  January  Acre              0.0  1/1/2008
11  2009  January  Acre              0.0  1/1/2009
12  2010  January  Acre              1.0  1/1/2010
13  2011  January  Acre              0.0  1/1/2011
14  2012  January  Acre              0.0  1/1/2012
15  2013  January  Acre              0.0  1/1/2013
16  2014  January  Acre              0.0  1/1/2014
17  2015  January  Acre              1.0  1/1/2015
18  2016  January  Acre             12.0  1/1/2016
19  2017  January  Acre              0.0  1/1/2017

# Using the groupby function

In [7]:
# first let's aggregrate date based on each state
# we'll create our groupby object
df.groupby('state')

In [9]:
# how do we do our object ? 
state_groups = df.groupby('state')
state_groups.get_group('Rio')

      year     month state  number_of_fires      date
4303  1998   January   Rio              0.0  1/1/1998
4304  1999   January   Rio              0.0  1/1/1999
4305  2000   January   Rio              0.0  1/1/2000
4306  2001   January   Rio              0.0  1/1/2001
4307  2002   January   Rio              0.0  1/1/2002
...    ...       ...   ...              ...       ...
5015  2012  December   Rio             38.0  1/1/2012
5016  2013  December   Rio             62.0  1/1/2013
5017  2014  December   Rio             31.0  1/1/2014
5018  2015  December   Rio             42.0  1/1/2015
5019  2016  December   Rio             79.0  1/1/2016

[717 rows x 5 columns]

In [10]:
# let;s look at the groups we made
# it is a dictionary where each key coresponds to a state name 
# the values are the index ranges for each group
state_groups.groups

{'Acre': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...], 'Alagoas': [239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, ...], 'Amapa': [479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, ...], 'Amazonas': [718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, ...], 'Bahia': [957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999, 1000, 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022, 1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033, 1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044, 1045, 1046, 1047, 1048, 1049, 1050, 1051, 1052, 1053, 1054, 1055, 1056, ...], 'Ceara': [1196, 1197, 1198, 1199, 1200, 1201, 1202, 1203, 1204, 1205, 1206, 1207, 1208, 1209, 1210, 1211, 1212, 1213, 1214, 1215, 1216, 1217, 1218, 1219, 1220, 1221, 1222, 1223, 1224, 1225, 1226, 1227, 1228, 1229, 1230, 1231, 1232, 1233, 1234, 1235, 1236, 1237, 1238, 1239, 1240, 1241, 1242, 1243, 1244, 1245, 1246, 1247, 1248, 1249, 1250, 1251, 1252, 1253, 1254, 1255, 1256, 1257, 1258, 1259, 1260, 1261, 1262, 1263, 1264, 1265, 1266, 1267, 1268, 1269, 1270, 1271, 1272, 1273, 1274, 1275, 1276, 1277, 1278, 1279, 1280, 1281, 1282, 1283, 1284, 1285, 1286, 1287, 1288, 1289, 1290, 1291, 1292, 1293, 1294, 1295, ...], 'Distrito Federal': [1435, 1436, 1437, 1438, 1439, 1440, 1441, 1442, 1443, 1444, 1445, 1446, 1447, 1448, 1449, 1450, 1451, 1452, 1453, 1454, 1455, 1456, 1457, 1458, 1459, 1460, 1461, 1462, 1463, 1464, 1465, 1466, 1467, 1468, 1469, 1470, 1471, 1472, 1473, 1474, 1475, 1476, 1477, 1478, 1479, 1480, 1481, 1482, 1483, 1484, 1485, 1486, 1487, 1488, 1489, 1490, 1491, 1492, 1493, 1494, 1495, 1496, 1497, 1498, 1499, 1500, 1501, 1502, 1503, 1504, 1505, 1506, 1507, 1508, 1509, 1510, 1511, 1512, 1513, 1514, 1515, 1516, 1517, 1518, 1519, 1520, 1521, 1522, 1523, 1524, 1525, 1526, 1527, 1528, 1529, 1530, 1531, 1532, 1533, 1534, ...], 'Espirito Santo': [1674, 1675, 1676, 1677, 1678, 1679, 1680, 1681, 1682, 1683, 1684, 1685, 1686, 1687, 1688, 1689, 1690, 1691, 1692, 1693, 1694, 1695, 1696, 1697, 1698, 1699, 1700, 1701, 1702, 1703, 1704, 1705, 1706, 1707, 1708, 1709, 1710, 1711, 1712, 1713, 1714, 1715, 1716, 1717, 1718, 1719, 1720, 1721, 1722, 1723, 1724, 1725, 1726, 1727, 1728, 1729, 1730, 1731, 1732, 1733, 1734, 1735, 1736, 1737, 1738, 1739, 1740, 1741, 1742, 1743, 1744, 1745, 1746, 1747, 1748, 1749, 1750, 1751, 1752, 1753, 1754, 1755, 1756, 1757, 1758, 1759, 1760, 1761, 1762, 1763, 1764, 1765, 1766, 1767, 1768, 1769, 1770, 1771, 1772, 1773, ...], 'Goias': [1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, ...], 'Maranhao': [2152, 2153, 2154, 2155, 2156, 2157, 2158, 2159, 2160, 2161, 2162, 2163, 2164, 2165, 2166, 2167, 2168, 2169, 2170, 2171, 2172, 2173, 2174, 2175, 2176, 2177, 2178, 2179, 2180, 2181, 2182, 2183, 2184, 2185, 2186, 2187, 2188, 2189, 2190, 2191, 2192, 2193, 2194, 2195, 2196, 2197, 2198, 2199, 2200, 2201, 2202, 2203, 2204, 2205, 2206, 2207, 2208, 2209, 2210, 2211, 2212, 2213, 2214, 2215, 2216, 2217, 2218, 2219, 2220, 2221, 2222, 2223, 2224, 2225, 2226, 2227, 2228, 2229, 2230, 2231, 2232, 2233, 2234, 2235, 2236, 2237, 2238, 2239, 2240, 2241, 2242, 2243, 2244, 2245, 2246, 2247, 2248, 2249, 2250, 2251, ...], 'Mato Grosso': [2391, 2392, 2393, 2394, 2395, 2396, 2397, 2398, 2399, 2400, 2401, 2402, 2403, 2404, 2405, 2406, 2407, 2408, 2409, 2410, 2411, 2412, 2413, 2414, 2415, 2416, 2417, 2418, 2419, 2420, 2421, 2422, 2423, 2424, 2425, 2426, 2427, 2428, 2429, 2430, 2431, 2432, 2433, 2434, 2435, 2436, 2437, 2438, 2439, 2440, 2441, 2442, 2443, 2444, 2445, 2446, 2447, 2448, 2449, 2450, 2451, 2452, 2453, 2454, 2455, 2456, 2457, 2458, 2459, 2460, 2461, 2462, 2463, 2464, 2465, 2466, 2467, 2468, 2469, 2470, 2471, 2472, 2473, 2474, 2475, 2476, 2477, 2478, 2479, 2480, 2481, 2482, 2483, 2484, 2485, 2486, 2487, 2488, 2489, 2490, ...], 'Minas Gerais': [2869, 2870, 2871, 2872, 2873, 2874, 2875, 2876, 2877, 2878, 2879, 2880, 2881, 2882, 2883, 2884, 2885, 2886, 2887, 2888, 2889, 2890, 2891, 2892, 2893, 2894, 2895, 2896, 2897, 2898, 2899, 2900, 2901, 2902, 2903, 2904, 2905, 2906, 2907, 2908, 2909, 2910, 2911, 2912, 2913, 2914, 2915, 2916, 2917, 2918, 2919, 2920, 2921, 2922, 2923, 2924, 2925, 2926, 2927, 2928, 2929, 2930, 2931, 2932, 2933, 2934, 2935, 2936, 2937, 2938, 2939, 2940, 2941, 2942, 2943, 2944, 2945, 2946, 2947, 2948, 2949, 2950, 2951, 2952, 2953, 2954, 2955, 2956, 2957, 2958, 2959, 2960, 2961, 2962, 2963, 2964, 2965, 2966, 2967, 2968, ...], 'Paraiba': [3347, 3348, 3349, 3350, 3351, 3352, 3353, 3354, 3355, 3356, 3357, 3358, 3359, 3360, 3361, 3362, 3363, 3364, 3365, 3366, 3367, 3368, 3369, 3370, 3371, 3372, 3373, 3374, 3375, 3376, 3377, 3378, 3379, 3380, 3381, 3382, 3383, 3384, 3385, 3386, 3387, 3388, 3389, 3390, 3391, 3392, 3393, 3394, 3395, 3396, 3397, 3398, 3399, 3400, 3401, 3402, 3403, 3404, 3405, 3406, 3407, 3408, 3409, 3410, 3411, 3412, 3413, 3414, 3415, 3416, 3417, 3418, 3419, 3420, 3421, 3422, 3423, 3424, 3425, 3426, 3427, 3428, 3429, 3430, 3431, 3432, 3433, 3434, 3435, 3436, 3437, 3438, 3439, 3440, 3441, 3442, 3443, 3444, 3445, 3446, ...], 'Pará': [3108, 3109, 3110, 3111, 3112, 3113, 3114, 3115, 3116, 3117, 3118, 3119, 3120, 3121, 3122, 3123, 3124, 3125, 3126, 3127, 3128, 3129, 3130, 3131, 3132, 3133, 3134, 3135, 3136, 3137, 3138, 3139, 3140, 3141, 3142, 3143, 3144, 3145, 3146, 3147, 3148, 3149, 3150, 3151, 3152, 3153, 3154, 3155, 3156, 3157, 3158, 3159, 3160, 3161, 3162, 3163, 3164, 3165, 3166, 3167, 3168, 3169, 3170, 3171, 3172, 3173, 3174, 3175, 3176, 3177, 3178, 3179, 3180, 3181, 3182, 3183, 3184, 3185, 3186, 3187, 3188, 3189, 3190, 3191, 3192, 3193, 3194, 3195, 3196, 3197, 3198, 3199, 3200, 3201, 3202, 3203, 3204, 3205, 3206, 3207, ...], 'Pernambuco': [3825, 3826, 3827, 3828, 3829, 3830, 3831, 3832, 3833, 3834, 3835, 3836, 3837, 3838, 3839, 3840, 3841, 3842, 3843, 3844, 3845, 3846, 3847, 3848, 3849, 3850, 3851, 3852, 3853, 3854, 3855, 3856, 3857, 3858, 3859, 3860, 3861, 3862, 3863, 3864, 3865, 3866, 3867, 3868, 3869, 3870, 3871, 3872, 3873, 3874, 3875, 3876, 3877, 3878, 3879, 3880, 3881, 3882, 3883, 3884, 3885, 3886, 3887, 3888, 3889, 3890, 3891, 3892, 3893, 3894, 3895, 3896, 3897, 3898, 3899, 3900, 3901, 3902, 3903, 3904, 3905, 3906, 3907, 3908, 3909, 3910, 3911, 3912, 3913, 3914, 3915, 3916, 3917, 3918, 3919, 3920, 3921, 3922, 3923, 3924, ...], 'Piau': [4064, 4065, 4066, 4067, 4068, 4069, 4070, 4071, 4072, 4073, 4074, 4075, 4076, 4077, 4078, 4079, 4080, 4081, 4082, 4083, 4084, 4085, 4086, 4087, 4088, 4089, 4090, 4091, 4092, 4093, 4094, 4095, 4096, 4097, 4098, 4099, 4100, 4101, 4102, 4103, 4104, 4105, 4106, 4107, 4108, 4109, 4110, 4111, 4112, 4113, 4114, 4115, 4116, 4117, 4118, 4119, 4120, 4121, 4122, 4123, 4124, 4125, 4126, 4127, 4128, 4129, 4130, 4131, 4132, 4133, 4134, 4135, 4136, 4137, 4138, 4139, 4140, 4141, 4142, 4143, 4144, 4145, 4146, 4147, 4148, 4149, 4150, 4151, 4152, 4153, 4154, 4155, 4156, 4157, 4158, 4159, 4160, 4161, 4162, 4163, ...], 'Rio': [4303, 4304, 4305, 4306, 4307, 4308, 4309, 4310, 4311, 4312, 4313, 4314, 4315, 4316, 4317, 4318, 4319, 4320, 4321, 4322, 4323, 4324, 4325, 4326, 4327, 4328, 4329, 4330, 4331, 4332, 4333, 4334, 4335, 4336, 4337, 4338, 4339, 4340, 4341, 4342, 4343, 4344, 4345, 4346, 4347, 4348, 4349, 4350, 4351, 4352, 4353, 4354, 4355, 4356, 4357, 4358, 4359, 4360, 4361, 4362, 4363, 4364, 4365, 4366, 4367, 4368, 4369, 4370, 4371, 4372, 4373, 4374, 4375, 4376, 4377, 4378, 4379, 4380, 4381, 4382, 4383, 4384, 4385, 4386, 4387, 4388, 4389, 4390, 4391, 4392, 4393, 4394, 4395, 4396, 4397, 4398, 4399, 4400, 4401, 4402, ...], 'Rondonia': [5020, 5021, 5022, 5023, 5024, 5025, 5026, 5027, 5028, 5029, 5030, 5031, 5032, 5033, 5034, 5035, 5036, 5037, 5038, 5039, 5040, 5041, 5042, 5043, 5044, 5045, 5046, 5047, 5048, 5049, 5050, 5051, 5052, 5053, 5054, 5055, 5056, 5057, 5058, 5059, 5060, 5061, 5062, 5063, 5064, 5065, 5066, 5067, 5068, 5069, 5070, 5071, 5072, 5073, 5074, 5075, 5076, 5077, 5078, 5079, 5080, 5081, 5082, 5083, 5084, 5085, 5086, 5087, 5088, 5089, 5090, 5091, 5092, 5093, 5094, 5095, 5096, 5097, 5098, 5099, 5100, 5101, 5102, 5103, 5104, 5105, 5106, 5107, 5108, 5109, 5110, 5111, 5112, 5113, 5114, 5115, 5116, 5117, 5118, 5119, ...], 'Roraima': [5259, 5260, 5261, 5262, 5263, 5264, 5265, 5266, 5267, 5268, 5269, 5270, 5271, 5272, 5273, 5274, 5275, 5276, 5277, 5278, 5279, 5280, 5281, 5282, 5283, 5284, 5285, 5286, 5287, 5288, 5289, 5290, 5291, 5292, 5293, 5294, 5295, 5296, 5297, 5298, 5299, 5300, 5301, 5302, 5303, 5304, 5305, 5306, 5307, 5308, 5309, 5310, 5311, 5312, 5313, 5314, 5315, 5316, 5317, 5318, 5319, 5320, 5321, 5322, 5323, 5324, 5325, 5326, 5327, 5328, 5329, 5330, 5331, 5332, 5333, 5334, 5335, 5336, 5337, 5338, 5339, 5340, 5341, 5342, 5343, 5344, 5345, 5346, 5347, 5348, 5349, 5350, 5351, 5352, 5353, 5354, 5355, 5356, 5357, 5358, ...], 'Santa Catarina': [5498, 5499, 5500, 5501, 5502, 5503, 5504, 5505, 5506, 5507, 5508, 5509, 5510, 5511, 5512, 5513, 5514, 5515, 5516, 5517, 5518, 5519, 5520, 5521, 5522, 5523, 5524, 5525, 5526, 5527, 5528, 5529, 5530, 5531, 5532, 5533, 5534, 5535, 5536, 5537, 5538, 5539, 5540, 5541, 5542, 5543, 5544, 5545, 5546, 5547, 5548, 5549, 5550, 5551, 5552, 5553, 5554, 5555, 5556, 5557, 5558, 5559, 5560, 5561, 5562, 5563, 5564, 5565, 5566, 5567, 5568, 5569, 5570, 5571, 5572, 5573, 5574, 5575, 5576, 5577, 5578, 5579, 5580, 5581, 5582, 5583, 5584, 5585, 5586, 5587, 5588, 5589, 5590, 5591, 5592, 5593, 5594, 5595, 5596, 5597, ...], 'Sao Paulo': [5737, 5738, 5739, 5740, 5741, 5742, 5743, 5744, 5745, 5746, 5747, 5748, 5749, 5750, 5751, 5752, 5753, 5754, 5755, 5756, 5757, 5758, 5759, 5760, 5761, 5762, 5763, 5764, 5765, 5766, 5767, 5768, 5769, 5770, 5771, 5772, 5773, 5774, 5775, 5776, 5777, 5778, 5779, 5780, 5781, 5782, 5783, 5784, 5785, 5786, 5787, 5788, 5789, 5790, 5791, 5792, 5793, 5794, 5795, 5796, 5797, 5798, 5799, 5800, 5801, 5802, 5803, 5804, 5805, 5806, 5807, 5808, 5809, 5810, 5811, 5812, 5813, 5814, 5815, 5816, 5817, 5818, 5819, 5820, 5821, 5822, 5823, 5824, 5825, 5826, 5827, 5828, 5829, 5830, 5831, 5832, 5833, 5834, 5835, 5836, ...], 'Sergipe': [5976, 5977, 5978, 5979, 5980, 5981, 5982, 5983, 5984, 5985, 5986, 5987, 5988, 5989, 5990, 5991, 5992, 5993, 5994, 5995, 5996, 5997, 5998, 5999, 6000, 6001, 6002, 6003, 6004, 6005, 6006, 6007, 6008, 6009, 6010, 6011, 6012, 6013, 6014, 6015, 6016, 6017, 6018, 6019, 6020, 6021, 6022, 6023, 6024, 6025, 6026, 6027, 6028, 6029, 6030, 6031, 6032, 6033, 6034, 6035, 6036, 6037, 6038, 6039, 6040, 6041, 6042, 6043, 6044, 6045, 6046, 6047, 6048, 6049, 6050, 6051, 6052, 6053, 6054, 6055, 6056, 6057, 6058, 6059, 6060, 6061, 6062, 6063, 6064, 6065, 6066, 6067, 6068, 6069, 6070, 6071, 6072, 6073, 6074, 6075, ...], 'Tocantins': [6215, 6216, 6217, 6218, 6219, 6220, 6221, 6222, 6223, 6224, 6225, 6226, 6227, 6228, 6229, 6230, 6231, 6232, 6233, 6234, 6235, 6236, 6237, 6238, 6239, 6240, 6241, 6242, 6243, 6244, 6245, 6246, 6247, 6248, 6249, 6250, 6251, 6252, 6253, 6254, 6255, 6256, 6257, 6258, 6259, 6260, 6261, 6262, 6263, 6264, 6265, 6266, 6267, 6268, 6269, 6270, 6271, 6272, 6273, 6274, 6275, 6276, 6277, 6278, 6279, 6280, 6281, 6282, 6283, 6284, 6285, 6286, 6287, 6288, 6289, 6290, 6291, 6292, 6293, 6294, 6295, 6296, 6297, 6298, 6299, 6300, 6301, 6302, 6303, 6304, 6305, 6306, 6307, 6308, 6309, 6310, 6311, 6312, 6313, 6314, ...]}

In [11]:
# we can use size to get a count of the number of items in each group 
state_groups.size()

state
Acre                239
Alagoas             240
Amapa               239
Amazonas            239
Bahia               239
Ceara               239
Distrito Federal    239
Espirito Santo      239
Goias               239
Maranhao            239
Mato Grosso         478
Minas Gerais        239
Paraiba             478
Pará                239
Pernambuco          239
Piau                239
Rio                 717
Rondonia            239
Roraima             239
Santa Catarina      239
Sao Paulo           239
Sergipe             239
Tocantins           239
dtype: int64

# Let's now use some aggregation functions

###### mean()
###### size()
###### count()
###### sum()
###### min()
###### max()

In [15]:
state_groups.sum()

,year,month,number_of_fires,date
state,,,,
Acre,479783,JanuaryJanuaryJanuaryJanuaryJanuaryJanuaryJanu...,17971.030,1/1/19981/1/19991/1/20001/1/20011/1/20021/1/20...
Alagoas,481800,JanuaryJanuaryJanuaryJanuaryJanuaryJanuaryJanu...,4594.000,1/1/19981/1/19991/1/20001/1/20011/1/20021/1/20...
Amapa,479783,JanuaryJanuaryJanuaryJanuaryJanuaryJanuaryJanu...,20108.576,1/1/19981/1/19991/1/20001/1/20011/1/20021/1/20...
Amazonas,479783,JanuaryJanuaryJanuaryJanuaryJanuaryJanuaryJanu...,29890.129,1/1/19981/1/19991/1/20001/1/20011/1/20021/1/20...
Bahia,479783,JanuaryJanuaryJanuaryJanuaryJanuaryJanuaryJanu...,43411.951,1/1/19981/1/19991/1/20001/1/20011/1/20021/1/20...
Ceara,479783,JanuaryJanuaryJanuaryJanuaryJanuaryJanuaryJanu...,30395.042,1/1/19981/1/19991/1/20001/1/20011/1/20021/1/20...
Distrito Federal,479783,JanuaryJanuaryJanuaryJanuaryJanuaryJanuaryJanu...,3501.000,1/1/19981/1/19991/1/20001/1/20011/1/20021/1/20...
Espirito Santo,479783,JanuaryJanuaryJanuaryJanuaryJanuaryJanuaryJanu...,37002.276,1/1/19981/1/19991/1/20001/1/20011/1/20021/1/20...
Goias,479783,JanuaryJanuaryJanuaryJanuaryJanuaryJanuaryJanu...,23362.852,1/1/19981/1/19991/1/20001/1/20011/1/20021/1/20...
Maranhao,479783,JanuaryJanuaryJanuaryJanuaryJanuaryJanuaryJanu...,24839.169,1/1/19981/1/19991/1/20001/1/20011/1/20021/1/20...
Mato Grosso,959566,JanuaryJanuaryJanuaryJanuaryJanuaryJanuaryJanu...,95566.975,1/1/19981/1/19991/1/20001/1/20011/1/20021/1/20...
Minas Gerais,479783,JanuaryJanuaryJanuaryJanuaryJanuaryJanuaryJanu...,37002.276,1/1/19981/1/19991/1/20001/1/20011/1/20021/1/20...
Paraiba,959566,JanuaryJanuaryJanuaryJanuaryJanuaryJanuaryJanu...,51723.918,1/1/19981/1/19991/1/20001/1/20011/1/20021/1/20...
Pará,479783,JanuaryJanuaryJanuaryJanuaryJanuaryJanuaryJanu...,22124.144,1/1/19981/1/19991/1/20001/1/20011/1/20021/1/20...
Pernambuco,479783,JanuaryJanuaryJanuaryJanuaryJanuaryJanuaryJanu...,22959.000,1/1/19981/1/19991/1/20001/1/20011/1/20021/1/20...
Piau,479783,JanuaryJanuaryJanuaryJanuaryJanuaryJanuaryJanu...,37542.651,1/1/19981/1/19991/1/20001/1/20011/1/20021/1/20...
Rio,1439349,JanuaryJanuaryJanuaryJanuaryJanuaryJanuaryJanu...,44799.865,1/1/19981/1/19991/1/20001/1/20011/1/20021/1/20...
Rondonia,479783,JanuaryJanuaryJanuaryJanuaryJanuaryJanuaryJanu...,19239.429,1/1/19981/1/19991/1/20001/1/20011/1/20021/1/20...
Roraima,479783,JanuaryJanuaryJanuaryJanuaryJanuaryJanuaryJanu...,23749.074,1/1/19981/1/19991/1/20001/1/20011/1/20021/1/20...
Santa Catarina,479783,JanuaryJanuaryJanuaryJanuaryJanuaryJanuaryJanu...,23362.852,1/1/19981/1/19991/1/20001/1/20011/1/20021/1/20...
Sao Paulo,479783,JanuaryJanuaryJanuaryJanuaryJanuaryJanuaryJanu...,49888.198,1/1/19981/1/19991/1/20001/1/20011/1/20021/1/20...
Sergipe,479783,JanuaryJanuaryJanuaryJanuaryJanuaryJanuaryJanu...,3167.000,1/1/19981/1/19991/1/20001/1/20011/1/20021/1/20...
Tocantins,479783,JanuaryJanuaryJanuaryJanuaryJanuaryJanuaryJanu...,33441.509,1/1/19981/1/19991/1/20001/1/20011/1/20021/1/20...

## combining our groupby into one concise statement

In [17]:
df.groupby('state')['number_of_fires'].mean()

state
Acre                 75.192594
Alagoas              19.141667
Amapa                84.136301
Amazonas            125.063301
Bahia               181.639962
Ceara               127.175908
Distrito Federal     14.648536
Espirito Santo      154.821238
Goias                97.752519
Maranhao            103.929577
Mato Grosso         199.930910
Minas Gerais        154.821238
Paraiba             108.209033
Pará                 92.569640
Pernambuco           96.062762
Piau                157.082222
Rio                  62.482378
Rondonia             80.499703
Roraima              99.368510
Santa Catarina       97.752519
Sao Paulo           208.737230
Sergipe              13.251046
Tocantins           139.922632
Name: number_of_fires, dtype: float64

# Pivot tables

In [19]:
import numpy as np
df.pivot_table(values = 'number_of_fires', index = 'state', aggfunc = np.mean)

C:\Users\Acer\AppData\Local\Temp\ipykernel_12756\2848896869.py:2: FutureWarning: The provided callable <function mean at 0x0000024841B1A160> is currently using DataFrameGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  df.pivot_table(values = 'number_of_fires', index = 'state', aggfunc = np.mean)

                  number_of_fires
state
Acre                    75.192594
Alagoas                 19.141667
Amapa                   84.136301
Amazonas               125.063301
Bahia                  181.639962
Ceara                  127.175908
Distrito Federal        14.648536
Espirito Santo         154.821238
Goias                   97.752519
Maranhao               103.929577
Mato Grosso            199.930910
Minas Gerais           154.821238
Paraiba                108.209033
Pará                    92.569640
Pernambuco              96.062762
Piau                   157.082222
Rio                     62.482378
Rondonia                80.499703
Roraima                 99.368510
Santa Catarina          97.752519
Sao Paulo              208.737230
Sergipe                 13.251046
Tocantins              139.922632